server:
  port: 8080

spring:
  application:
    name: @project.build.finalName@
    version: @project.version@

tokens:
  access-token:
    expiration-time-ms: 300000
  refresh-token:
    expiration-time-ms: 30000000
    property: access-token-expiration-date-ms
  prefix: Bearer